name: bwu_ng_elements
version: 0.1.0
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: Reusable components for Angular 2.
homepage: https://github.com/bwu-dart/bwu_ng_elements
environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  angular2: ^2.0.0-beta
  browser: ^0.10.0
#  sass: '^0.4.2'

dev_dependencies:
  dart_to_js_script_rewriter: ^0.1.0
  bwu_sass_transformer:
    path: ../bwu_sass_transformer
  bwu_grinder_tasks: '^0.1.0'
transformers:
# transformer options
# https://github.com/angular/angular/blob/master/modules_dart/transform/lib/src/transform/common/options.dart#L20
transformers:
#- sass
- bwu_sass_transformer
#    executable: /usr/local/bin/sass    # Sass executable to use
#    compass: false                # Include compass
#    line-numbers: true            # Include line numbers in output
#    style: compact                # Style of generated CSS
#    copy-sources: false           # Copy original .scss/.sass files to output directory
- angular2:
    entry_points:
    - example/icon/main.dart
    - example/icons/main.dart
    - example/item/main.dart
    mirror_mode: verbose
    platform_pipes: 'package:angular2/common.dart#COMMON_PIPES'
# https://github.com/angular/angular/blob/3191fd144016c0873de4e3e24f0d8695a7d101c2/modules/angular2/src/common/pipes.ts
    gen_change_detection_debug_info: true
    platform_directives: 'package:angular2/common.dart#COMMON_DIRECTIVES'
#    platform_directives: 'package:angular2/common.dart/directives.dart#FORM_DIRECTIVES'
- $dart2js:
    minify: true
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
- dart_to_js_script_rewriter
